version: '3'
services:
  single-spa-root-config:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:90" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
